model = "gpt-5.3-codex"
model_reasoning_effort = "high"
personality = "friendly"
approval_policy = "never"
sandbox_mode = "danger-full-access"
[projects."/Users/tal"]
trust_level = "trusted"

[projects."/Users/tal/projects/pigai_eval"]
trust_level = "trusted"

[projects."/Users/tal/Downloads"]
trust_level = "trusted"

[projects."/Users/tal/projects/charting_library-master"]
trust_level = "trusted"

[projects."/Users/tal/Downloads/1016-1211学习机竞品横评批改+拆录处理后数据"]
trust_level = "trusted"

[projects."/Users/tal/projects/trade-practice"]
trust_level = "trusted"

[projects."/Users/tal/.codex/skills"]
trust_level = "trusted"

[projects."/Users/tal/.codex/skills/rknn_sdk_doc"]
trust_level = "trusted"

[projects."/Users/tal/Downloads/doc"]
trust_level = "trusted"

[projects."/Users/tal/.codex"]
trust_level = "trusted"

[projects."/Users/tal/TensorRT-LLM-Docs/output/TensorRT-LLM/1.1.0"]
trust_level = "trusted"

[projects."/Users/tal/PycharmProjects/ai_demo"]
trust_level = "trusted"

[projects."/Users/tal/projects"]
trust_level = "trusted"

[projects."/Users/tal/auto-miner"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.4"
"gpt-5.1-codex-mini" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
unified_exec = true
shell_snapshot = true
steer = true
apps = true
personality = true
multi_agent = true

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[[skills.config]]
path = "/Users/tal/.codex/skills/tensorrt-llm-docs-1-3-0rc7/SKILL.md"
enabled = false

[plugins."github@openai-curated"]
enabled = true

[plugins."jam@openai-curated"]
enabled = true
